title: phpdaily - Unofficial Docker image packing nightly builds
email: contact@jdecool.fr
description: >- # this means to ignore newlines until "baseurl:"
  phpdaily/php is a collection of the daily updated Docker images for a variety of PHP versions. 
  These include even the most recent development versions.
baseurl: ""
url: "https://phpdaily.github.io"
permalink: /blog/:year/:month/:day/:title.html
twitter_username: phpdaily
github_username: phpdaily

excerpt_separator: <!--more-->

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
